version: '2'

services:
  nginx_bar:
    image: register.fidelize.com.br/desenvolvimento/nginx
    container_name: nginx_bar
    restart: always
    volumes:
      - ./docker/nginx_conf:/etc/nginx/conf.d
      - ./:/var/www/html/
    links:
      - php_bar:php
    networks:
      projetos_micro_servicos:
        ipv4_address: 10.11.0.111

  php_bar:
    image: register.fidelize.com.br/desenvolvimento/php:7.1
    container_name: php_bar
    restart: always
    command: bash -c "sed -i \"s/memory_limit = 128M/memory_limit = 999999999999M/\" /usr/local/etc/php/php.ini && sed -i \"s/short_open_tag = Off/short_open_tag = On/\" /usr/local/etc/php/php.ini && sed -i \"s/max_execution_time = 30/max_execution_time = 300/\" /usr/local/etc/php/php.ini && php-fpm"
    environment:
      - XDEBUG_CONFIG=remote_host=172.17.0.1
    volumes:
      - ./:/var/www/html
      - /usr/bin/ssh:/usr/bin/ssh
    networks:
      projetos_micro_servicos:
        ipv4_address: 10.11.0.112

#  mysql:
#    image: mysql:5.7
#    container_name: mysql
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=A123456
#      - MYSQL_DATABASE=webadm
#      - MYSQL_USER=webadm
#      - MYSQL_PASSWORD=A123456
#      # - MYSQL_ROOT_HOST=%
#    volumes:
#      - ./volumes/mysql57novo:/var/lib/mysql
#      - ./volumes/mysql57conf:/etc/mysql/mysql.conf.d
#    networks:
#      micro_servicos:
#        ipv4_address: 10.11.0.113

networks:
  projetos_micro_servicos:
    external: true
